findanswer/Controllers/FirstPageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using findanswer.Models;
using findanswer.Controllers;

namespace findanswer.Controllers
{
    public class FirstPageController : Controller
    {

        //对于web.config中不存放connectstring的处理
        private FindAnswerMsSqlModel db = new FindAnswerMsSqlModel(FindAnswerMsSqlModel.conn);
        
        // GET: FirstPage
        public ActionResult Default()
        {
            ViewBag.Message = "帮助您在这里找到你需要的考试答案.";

            //findanswer.Models.FirstPageModel test = new findanswer.Models.FirstPageModel();
            //string a = test.a.ToString();
            //ViewBag.Message = a;

            //return View();
            return View(db.Cat.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "帮助您在这里找到你需要的考试答案.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "帮助您在这里找到你需要的考试答案.";

            return View();
        }

        public ActionResult ClickList(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Cat cat = db.Cat.Find(id);
            //if (cat == null)
            //{
            //    return HttpNotFound();
            //}
            return View();
        }


    }
}

findanswer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 找答案 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

findanswer/Views/Shared/_LayoutForFindanswer.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Staticfile CDN 上的 Bootstrap 核心 CSS 文件 -->
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <title>@ViewBag.Title </title>

</head>

<body>
    <div class="navbar navbar-default">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("找答案网", "Default", "FirstPage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Default", "FirstPage")</li>
                    <li>@Html.ActionLink("关于", "About", "FirstPage")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "FirstPage")</li>
                </ul>
            </div>
            <div></div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer class="text-center">           
            <p>&copy; @DateTime.Now.Year - www.findanswer.cn - 找答案网 &nbsp;&nbsp; 苏ICP备00000000号 - <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=0">苏公网安备 00000000号</a></p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

findanswer/Views/Shared/_LayoutForSearch.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Staticfile CDN 上的 Bootstrap 核心 CSS 文件 -->
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <title>@ViewBag.Title </title>

</head>

<body>
    <div class="navbar navbar-default">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("找答案网", "Default", "FirstPage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Default", "FirstPage")</li>
                    <li>@Html.ActionLink("关于", "About", "FirstPage")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "FirstPage")</li>
                </ul>
            </div>
            <div></div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer class="text-center">
            <p>
                <a target="_blank" href="/about/index.html">关于我们</a><span>
                    |
                </span><a target="_blank" href="/about/contact.html">接口开放</a><span>
                    |
                </span><a target="_blank" href="/about/copyright.html">网站声明</a><span>
                    |
                </span><a target="_blank" href="/about/contact.html">合作共赢</a>
            </p>
            <p>&copy; @DateTime.Now.Year - www.findanswer.cn - 找答案网 &nbsp;&nbsp; 苏ICP备14008899号 - <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=14118102000122">苏公网安备 14118102000122号</a></p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>